// #region Imports

/*
	https://svelte.dev/docs/kit/integrations#preprocessors
	Import the preprocessor to allow the use of SCSS
*/
import { sveltePreprocess } from "svelte-preprocess"

/*
	https://svelte.dev/docs/kit/adapters
	Import the correct adapter for Node servers.
	Some tricks are needed to use Deno to run the Node server, but Deno is 
	mostly backwards-compatible with Node. The deno.json file just has to 
	specify some of the npm packages that are used in the Node server.
*/
import adapter from "@sveltejs/adapter-node"

// Import to get file paths
import { fileURLToPath } from "node:url"

// #endregion Imports



// Define directories
const webDirURL = new URL("./web/", import.meta.url)
const srcDirURL = new URL("./src/", webDirURL)


/*
	https://svelte.dev/docs/kit/configuration
	Define Svelte config
*/
/** @type {import("@sveltejs/kit").Config} */
const config = {

	// Preprocessor settings
	preprocess: [
		sveltePreprocess()
	],

	// SvelteKit settings
	kit: {
		adapter: adapter({
			// The directory to build the Node server
			out: fileURLToPath(new URL(
				"./build",
				webDirURL
			)),

			// Prefix for environment variables used by the Node server
			envPrefix: "NODE_SERVER_",
		}),

		// The directory for SvelteKit to write temp files and cache
		outDir: fileURLToPath(new URL(
			"./.svelte-kit",
			webDirURL
		)),
		
		env: {
			/*
				Prefix for environment variables that are safe/unsafe
				to expose client-side
			*/
			publicPrefix: "PUBLIC_",
			privatePrefix: ""
		},
		
		files: {
			appTemplate: fileURLToPath(new URL(
				"./app.html",
				srcDirURL
			)),
			lib: fileURLToPath(new URL(
				"./lib",
				srcDirURL
			)),
			assets: fileURLToPath(new URL(
				"./lib/static",
				srcDirURL
			)),
			hooks: {
				client: fileURLToPath(new URL(
					"./hooks.client",
					srcDirURL
				)),
				server: fileURLToPath(new URL(
					"./hooks.server",
					srcDirURL
				)),
				universal: fileURLToPath(new URL(
					"./hooks",
					srcDirURL
				))
			},
			params: fileURLToPath(new URL(
				"./params",
				srcDirURL
			)),
			routes: fileURLToPath(new URL(
				"./routes",
				srcDirURL
			)),
			serviceWorker: fileURLToPath(new URL(
				"./service-worker",
				srcDirURL
			)),
		},

		typescript: {
			// Make changes to the tsconfig generated by SvelteKit
			config: (tsconfig) => {
				tsconfig.compilerOptions.allowImportingTsExtensions = true

				return tsconfig
			}
		}
	}

}

// Export Svelte config
export default config