// #region Imports

import { fileURLToPath, URL } from "node:url"

import { sveltePreprocess } from "svelte-preprocess"
import adapter from "@sveltejs/adapter-node"

// #endregion Imports



// Define directories
const thisDirURL = new URL("./", import.meta.url)
const srcDirURL = new URL("./src/", thisDirURL)


/*
	https://svelte.dev/docs/kit/configuration
	Define Svelte config
*/
/** @type {import("@sveltejs/kit").Config} */
const config = {

	// Use Svelte5 syntax
	compilerOptions: { runes: true },

	// Preprocessor settings
	preprocess: [
		sveltePreprocess()
	],

	// SvelteKit settings
	kit: {
		adapter: adapter({
			// The directory to build the Node server
			out: fileURLToPath(new URL(
				"./app/build",
				thisDirURL
			)),

			// Prefix for environment variables used by the Node server
			envPrefix: "NODE_SERVER_",
		}),

		// The directory for SvelteKit to write temp files and cache
		outDir: fileURLToPath(new URL(
			"./.svelte-kit",
			thisDirURL
		)),
		
		env: {
			/*
				Prefix for environment variables that are safe/unsafe
				to expose client-side
			*/
			publicPrefix: "PUBLIC_",
			privatePrefix: ""
		},
		
		files: {
			appTemplate: fileURLToPath(new URL(
				"./app.html",
				srcDirURL
			)),
			lib: fileURLToPath(new URL(
				"./lib",
				srcDirURL
			)),
			assets: fileURLToPath(new URL(
				"./lib/static",
				srcDirURL
			)),
			hooks: {
				client: fileURLToPath(new URL(
					"./hooks/client",
					srcDirURL
				)),
				server: fileURLToPath(new URL(
					"./hooks/server",
					srcDirURL
				)),
				universal: fileURLToPath(new URL(
					"./hooks/universal",
					srcDirURL
				))
			},
			params: fileURLToPath(new URL(
				"./params",
				srcDirURL
			)),
			routes: fileURLToPath(new URL(
				"./routes",
				srcDirURL
			)),
			serviceWorker: fileURLToPath(new URL(
				"./service-worker",
				srcDirURL
			)),
		},

		typescript: {
			// Make changes to the tsconfig generated by SvelteKit
			config: (tsconfig) => {
				// tsconfig.compilerOptions.allowImportingTsExtensions = true

				return tsconfig
			}
		}
	}

}

// Export Svelte config
export default config